### ISSUE TITLE
Enable the disconnect button

### ISSUE THREAD

**Issue by euharrison** [anoma/namada-interface#1024]
Enable the disconnect button on the account indicator, backing to the state of extension not connected

![Screenshot 2024-08-20 at 12 52 18 (2)](https://github.com/user-attachments/assets/a496ed2d-2031-4a4a-8eb5-288e42148059)

![Screenshot 2024-08-20 at 13 07 00 (1)](https://github.com/user-attachments/assets/9031f194-e8fc-4927-93ff-b99abcd62d57)

**Comment by jurevans** [comment]
Closed as finished!
