### ISSUE TITLE
Show only the skated NAMs that are not unbonding

### ISSUE THREAD

**Issue by euharrison** [anoma/namada-interface#1025]
Namadillo treats the NAM currently in “unbonding” period as “staked”, so the UI mistakenly lets me unstake it again
however, when I click unstake, it does give me an error below

We need to show only the skated NAMs that are not unbonding

![Screenshot 2024-08-20 at 14 48 09](https://github.com/user-attachments/assets/823bb1a0-9fd6-43f8-92f3-457d3275de81)

**Comment by jurevans** [comment]
Closed as finished!
