### ISSUE TITLE
Namadillo: Syncing indicator sometimes shows epoch and block height as "undefined"

### ISSUE THREAD

**Issue by emccorson** [anoma/namada-interface#1072]
When you hover over the syncing indicator, sometimes it shows "Fully synced: height undefined, epoch undefined".

I'm not sure if this was caused by a network error when I encountered this issue, but it should be possible to handle the case in Namadillo.

**Comment by jurevans** [comment]
I'm gonna go ahead and close this, I don't believe this has been an issue for a while now!
