### ISSUE TITLE
Define Extension Actions for permissions

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#116]
That can be prompted when connecting.

* accounts
  * list all accounts
  * see account details
  * see balances
* transactions
  * suggest transactions to approve
    * TODO: define types?

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/2773320/195324867-5ffb428d-8711-421c-8479-6f3b552721d4.png">

**Comment by jurevans** [comment]
Closing, will discuss with product the requirements for permissions management
