### ISSUE TITLE
SDK: Shielded-Sync should broadcast events

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#1206]
When shielded sync starts, we should transmit progress events (`ProgressBar`) that contains:

- `current` 
- `total`

More info TBD

**Comment by euharrison** [comment]
Currently, the loading skeleton will be displayed to user while we are shield syncing

This is expected as it could take a huge amount of time (several minutes) depending on how many blocks the interface need to syncs

When we have the progress events transmitted, we can improve the interface adding a progress bar.

It's important to notice that it'll *not* going to have impact in the time consumed to sync, it's only a user friendly feedback while this is syncing

![Screenshot 2024-11-13 at 14 09 03](https://github.com/user-attachments/assets/f8d0b41b-61d3-47c8-9b8c-41c46ad04775)

![Screenshot 2024-11-13 at 14 09 13](https://github.com/user-attachments/assets/20a3c63a-cad4-4516-8386-2e7d5d09e204)
