### ISSUE TITLE
Extension: Update storage to use XChaChaPoly

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#124]
Due to a potential (but rare) [attack](https://www.usenix.org/system/files/sec22summer_albertini.pdf) on AES-GCM, we should instead use XChaChaPoly for our symmetric encryption.

In the extension, the background scripts class for `KeyRing` is encrypted data for storage using the [aes_gcm](https://docs.rs/aes-gcm/latest/aes_gcm/) crate.

A better option would be an implementation of `XChaChaPoly`, which for Rust can be found at:

- https://docs.rs/orion/latest/orion/aead/index.html

We currently have a simple `aead` utility in `@anoma/crypto` which uses `orion::aead`, so we can start there.

### Changes

The two places that will need to be updated are:

`Crypto.encrypt(...)`:
https://github.com/anoma/namada-interface/blob/f057a4fec6a479a8dfdb26947bb4ad443b74dc8f/apps/extension/src/background/keyring/crypto.ts#L22-L23

and:

`Crypto.decrypt(...)`:
https://github.com/anoma/namada-interface/blob/f057a4fec6a479a8dfdb26947bb4ad443b74dc8f/apps/extension/src/background/keyring/crypto.ts#L59-L61

In `@anoma/crypto`, we can take out `lib/src/crypto/aes.rs`, as these are the only places where it is used. As such, we need to update the tests.

### References

- https://www.usenix.org/system/files/sec22summer_albertini.pdf
- https://docs.rs/aes-gcm/latest/aes_gcm/
- https://docs.rs/orion/latest/orion/aead/index.html

**Comment by mateuszjasiuk** [comment]
Audit did not consider this a problem
