### ISSUE TITLE
Staking, Governance, Public Goods Funding - Fetch Validators

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#126]
The validators should be fetched with data regarding their voting power and any other details that are to be displayed in the UI. This does not include the data that is not stored on the chain (website and logo).

in the CLI the equivalent is the below and can be found on [testing sheet](https://docs.google.com/spreadsheets/d/1Je4movJMWqrDbLCwj0tCUuZlgN878oYmKc_-XkjszQ8/edit#gid=1801116219&range=A30):
```bash
./namada client voting-power
```

The UI and redux contains this already with fake data and can be found at https://github.com/anoma/namada-interface/blob/main/apps/namada-interface/src/slices/StakingAndGovernance/actions.ts#L72

**Comment by jurevans** [comment]
Closing as done
