### ISSUE TITLE
BUG: Namadillo - Not displaying balance for Shielded Assets in Shielded Overview

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#1269]
On the MASP overview `/masp`, we are not seeing balances when the same accounts display balance in the CLI.

This was reported on the DryRun Namadillo: https://interface.namada-dryrun.tududes.com/

MASP Indexer URL: `https://masp.namada-dryrun.tududes.com`

**Comment by euharrison** [comment]
Should be fixed by https://github.com/anoma/namada-interface/pull/1212

**Comment by euharrison** [comment]
we also need to confirm that the extension is updated and providing the `viewingKey`
