### ISSUE TITLE
Staking, Governance, Public Goods Funding - Fetching own bonding positions

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#127]
This includes the calls to:
* check the bonds of an address

in the CLI the equivalent is the below and can be found on [testing sheet](https://docs.google.com/spreadsheets/d/1Je4movJMWqrDbLCwj0tCUuZlgN878oYmKc_-XkjszQ8/edit#gid=1801116219&range=A33):
```bash
./namada client bonds --owner address_alias-established
```

The state management for this is already in the app and can be found at:
https://github.com/anoma/namada-interface/blob/main/apps/namada-interface/src/slices/StakingAndGovernance/actions.ts#L88

**Comment by jurevans** [comment]
Closing as done
