### ISSUE TITLE
BUG: Namadillo - IBC token balance in overview does not update on Shielded Deposit success

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#1273]
This bug was reported on Discord. 

> on the MASP deposit screen, Namadillo does recognize that i now have 4.97 OSMO, so the
> 0.03 OSMO tx fee was deducted. the Overview screen still shows 5 OSMO

### Screenshots

<img width="528" alt="shielded-osmo" src="https://github.com/user-attachments/assets/e863ed27-34a3-4cd8-9111-5dbfbe1757c4">

<img width="975" alt="token-overview" src="https://github.com/user-attachments/assets/f669a251-14bb-410a-a615-daf5b29aeb6b">

**Comment by euharrison** [comment]
This is actually correct, we are subtracting the **Transaction Fee** from the **Balance** to define the **Available** amount to be transferred

In the example, if you have 5 OSMO, you can only Shield 4.97 because you will need to pay the fee of 0.03
