### ISSUE TITLE
Namadillo: governance proposal ordering is buggy

### ISSUE THREAD

**Issue by brentstone** [anoma/namada-interface#1280]
The ordering of governance proposals seems random and should be ordered. My opinion is that it should be the most recent (largest number) at top and decreasing down the bottom.
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/0bb4716d-021e-425f-a513-43e0dacadc39">

**Comment by emccorson** [comment]
This should be an indexer issue since Namadillo gets the paginated proposals from the indexer.
