### ISSUE TITLE
Missing IBC and transfer buttons in the transparent overview UI

### ISSUE THREAD

**Issue by ChrisHoltDesign** [anoma/namada-interface#1286]
<img width="887" alt="Screenshot 2024-11-20 at 16 59 06" src="https://github.com/user-attachments/assets/bb726acb-354d-4f8c-9aa1-19781d741f5c">

**Comment by brentstone** [comment]
@ChrisHoltDesign @pedrorezende @euharrison any progress here? This seems to me to be a Phase 3 nice-to-have and not a strict blocker.

@ChrisHoltDesign can you clarify what the needs are here and possibly provide the latest design? Assuming the two buttons you want to add are the two right-most buttons.

**Comment by ChrisHoltDesign** [comment]
@brentstone The first screenshot is correct. With the 2 symbol buttons missing on the right hand side. 

Definitely not a blocker so can be reduced in priority. 

Just good for UX as we don't have a specific withdraw button elsewhere. Users need to manually use the 'from namada' tab and input and select assets.
