### ISSUE TITLE
BUG: Namadillo - Shielded Tab Showing Transparent Balance

### ISSUE THREAD

**Issue by HadesGuard** [anoma/namada-interface#1289]
**Description**
In the transfer interface, the Shielded tab incorrectly displays the balance of the Transparent wallet instead of the actual Shielded wallet balance.

**Steps to Reproduce**
Open the transfer interface.
Navigate to the Shielded tab.
Select $NAM and observe the displayed balance.

**Expected Behavior**
The Shielded tab should display the correct balance of the Shielded wallet.

**Observed Behavior**
The Shielded tab shows the balance of the Transparent wallet.
<img width="608" alt="image" src="https://github.com/user-attachments/assets/fac72838-b737-421e-a496-47651e5c977c">

**Comment by euharrison** [comment]
we need to create a condition for extension 0.3.2 to use the prop `owner` instead of `viewingKey`
