### ISSUE TITLE
Namada Transparent to Namada Shielded Error: Invalid address encoding: expected 43 bytes for the payment address

### ISSUE THREAD

**Issue by msobh13** [anoma/namada-interface#1299]
Namada Transparent to Namada Shielded

Error: Invalid address encoding: expected 43 bytes for the payment address

see attached image
<img width="677" alt="Screenshot 2024-11-21 233920" src="https://github.com/user-attachments/assets/660a241d-7276-4d73-9018-141fd7ae3076">

`Namadillo Version: 0.2.1
SDK Version: 0.10.0`

**Comment by euharrison** [comment]
fixed by #1319
