### ISSUE TITLE
Unify MASP code between CLI and web client

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#13]
# Description
The logic between the MASP functionality between web client and CLI are pretty much the same. With little refactoring in core codebase the logic could be shared and lots of code that is now only for the web client could be get rid of.

If method would be refactored so that any side effects would be extracted it, only leaving the scanning and transaction generation logic it could be reused.
```rust
// https://github.com/anoma/anoma/blob/30fcf5c6e22cdb8f6fc3f2bb1ce58f705e4e8f13/apps/src/lib/client/tx.rs#L821
async fn gen_shielded_transfer(
    ctx: &mut Context,
    args: &args::TxTransfer,
) -> Result<Option<(Transaction, TransactionMetadata)>, builder::Error>
```
This refactoring needs good coordination with the devs in the core as these features might not yet be in a stable state.

# Outcomes
* a PR for implementing this change to Anoma branch
* a PR for implementing thse changes in the web specific Rust code

**Comment by memasdeligeorgakis** [comment]
Understand the APIs of extension account and key creation and map it to the creating of MASP transfer based on Namada core code base as much as possible.

**Comment by jurevans** [comment]
Closing as this is a part of the SDK, and `masp-web` is dead.
