### ISSUE TITLE
Staking, Governance, Public Goods Funding - Withdraw unbonded funds UI and app state

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#130]
When the user unbonds, the funds must be withdrawn to make them available for spending. The designs will be linked to this task once they exist. They will be listed in the Bonding dashboard in the table displaying active bonding positions. There is a [comment](https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU?node-id=9259:15554#290810274) about it, but it is incomplete.

**Comment by jurevans** [comment]
Closing as done
