### ISSUE TITLE
Disconnect Keychain extension button doesn't work - Keplr should also be available to disconnect 

### ISSUE THREAD

**Issue by ChrisHoltDesign** [anoma/namada-interface#1303]
<img width="311" alt="Screenshot 2024-11-22 at 09 38 20" src="https://github.com/user-attachments/assets/607480e6-1f22-4bd5-b2da-0c20e3130ee1">

**Comment by ChrisHoltDesign** [comment]
<img width="742" alt="Screenshot 2024-11-19 at 10 23 17" src="https://github.com/user-attachments/assets/913cacd5-b528-40be-87a4-c3b779bd289d">

**Comment by ChrisHoltDesign** [comment]
Make buttons bigger as per figma design tags

**Comment by euharrison** [comment]
The disconnect from Namada needs the extensions 0.3.3 to work. If the user has the 03.2 (Chrome Store) it'll not work
