### ISSUE TITLE
Staking, Governance, Public Goods Funding - Withdraw unbonded

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#131]
When the user unbonds, the funds must be withdrawn to make them available for spending. This includes:
* Query the withdrawal status
* Calls to withdraw funds

in the CLI the equivalent is the below and can be found on [testing sheet](https://docs.google.com/spreadsheets/d/1Je4movJMWqrDbLCwj0tCUuZlgN878oYmKc_-XkjszQ8/edit#gid=1801116219&range=A30):
```bash
./namada client withdraw --source address_alias-established --validator validatorAddress --amount 5
```

The UI and the the app state for this feature are not in the app yet, they will be implemented by: https://github.com/anoma/namada-interface/issues/130.

**Comment by jurevans** [comment]
Closing this, as this functionality is complete
