### ISSUE TITLE
Extension - Settings

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#134]
This contains the settings for the extension. It should be split into more specific tickets when worked on.

As a user
* I can always access settings from the settings icon when the UI is not locked
* I can reset and delete all the data from the extension. In this case, I will see a very clear warning about a possible risk of losing funds if I have not saved my seed phrase
* I can select to be connected to various chains and can change them from a dropdown element
* I can export my seed phrase, it is protected by the UI password even if the UI is already unlocked

User stories in HackMD
https://hackmd.io/V7Fwwm3XR1e0aBw42MHsfg?view#Settings
*Contains a feature that is not in scope in this task: Changing avatar*

Designs
overview - https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?node-id=9658%3A11632
password prompt - https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?node-id=9658%3A11866
seed phrase - https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?node-id=9658%3A11954

Click through demo
https://www.figma.com/proto/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?page-id=9219%3A14522&node-id=9658%3A11632&starting-point-node-id=9658%3A11632&scaling=scale-down&show-proto-sidebar=1

**Comment by mateuszjasiuk** [comment]
Waiting for the new designs
