### ISSUE TITLE
Change button roll over states from black to white

### ISSUE THREAD

**Issue by ChrisHoltDesign** [anoma/namada-interface#1342]
Currently rollover in buttons makes them dissapear black on black

Either rollover states are white or we make a white keyline on the black
<img width="176" alt="Screenshot 2024-11-28 at 20 45 35" src="https://github.com/user-attachments/assets/657a9849-ba20-4869-91b7-5b709b78706e">
<img width="327" alt="Screenshot 2024-11-28 at 20 45 41" src="https://github.com/user-attachments/assets/285e8ea4-ef1a-43cb-9443-5be779bb30e2">

**Comment by euharrison** [comment]
@ChrisHoltDesign how about urls like `/staking/bonding/increment?validator=MyAwesomeValidator` or `/staking/bonding/increment?validator=tnam123` and this value will be on the search box, so user could clear it later

**Comment by ChrisHoltDesign** [comment]
@euharrison Maybe we could add a keyline on rollover instead?

<img width="249" alt="Screenshot 2024-12-07 at 12 21 01" src="https://github.com/user-attachments/assets/1929621a-0b12-424f-8bd0-41ba5c3913f2">
<img width="598" alt="Screenshot 2024-12-07 at 12 22 15" src="https://github.com/user-attachments/assets/8bc57ed8-c777-4132-97c6-e2cf1ac5c6f5">

**Comment by brentstone** [comment]
What's the latest progress here? @ChrisHoltDesign @euharrison
