### ISSUE TITLE
Locked Keychain Allows Namadillo Login/Logout

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada-interface#1349]
It is possible log in and log out of Namadillo despite the keychain extension being locked, even after clearing site data. 

![image](https://github.com/user-attachments/assets/0e0c387c-bfc4-46a7-ab77-4e77271634cc)

![image](https://github.com/user-attachments/assets/21479cb9-5109-4b05-a2a4-1a5643f15584)

![image](https://github.com/user-attachments/assets/7343bb07-f110-425f-ab3b-52b0e5fd387f)

![image](https://github.com/user-attachments/assets/7a3b34a4-ca8b-4c9a-a61b-ee692fb72181)

**Comment by amadison79** [comment]
I tested it on my side and encountered the same problem...

**Comment by Rigorously** [comment]
The keychain stores information in IndexedDB, including the addresses, aliases, public keys, payment addresses, viewing keys in plaintext. To prevent data leakage on shared devices, perhaps that should be encrypted with the keychain password.

**Comment by jurevans** [comment]
@Rigorously thanks for reporting this! The existing behavior is what we intended, but after discussing this, we will implement this.
