### ISSUE TITLE
Show list of verified public interfaces in the keychain

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada-interface#1374]
- There are many fake Namadillo links circulating on X.
- Users are accustomed to web3 wallets wonder why the Keychain does not show balances and has no swap functionality.

Therefore I suggest to show a list of verified public interfaces in the Keychain.

**Comment by ChrisHoltDesign** [comment]
There's some legal barriers with showing balances and linking to various interfaces in the extension itself, hence why it's not been implemented as it makes total sense. 

A current proposed work around is to have the namada.help page linked at the bottom of the extension UI that can then show a list of verified interfaces

**Comment by euharrison** [comment]
https://github.com/anoma/namada-interface/issues/1383

**Comment by Rigorously** [comment]
Closing because of the workaround.
