### ISSUE TITLE
Namadillo: Add current time/date on dashboard

### ISSUE THREAD

**Issue by dismad** [anoma/namada-interface#1426]
![Screenshot_2024-12-18_20-59-31](https://github.com/user-attachments/assets/8539f683-bcc3-4e77-83f7-e04b542a1fa1)

# Problem
Live proposals have a date ending time posted but its unclear what the current time of the interface is

# Solution

Add a *current* date/time label some where on the dashboard

**Comment by euharrison** [comment]
I can add same solution as Github, adding the `title` attribute that shows the timezone on hover.
I hope it helps to communicate better :)

![Screenshot 2024-12-17 at 15 10 23](https://github.com/user-attachments/assets/ad086295-bb07-4b9f-84dc-40dc7ff00453)
