### ISSUE TITLE
Define type and decoding for the response when checking that Tx was applied

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#163]
When submitting a Tx to the chain, we can check whether it was applied by calling the `/shell/applied/txHash` path with abci query. The data in the response is not critical so as an MVP solution we are just checking whether the has is not the null value and is actually found and the client can know that the Tx was applied.

```ts
const abciResponse: AbciResponse = getResponse();
const wasFound = abciResponse.value !== "AA==";
```

also notice: https://github.com/anoma/namada-interface/issues/4#issuecomment-1342977235

**Comment by jurevans** [comment]
Closing as we are using SDK now, and not issuing these queries
