### ISSUE TITLE
EPIC: Introduce Namada SDK to Namada Web Client

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#177]
This Epic contains the work for starting to use Namada SDK in web client. Namada SDK is an attempt to offer a more clean and maintainable surface from Namada codebase. In the past the web client used to use exposed types and then develop features based on those, trying to replicate the functionality of the CLI.

This was working but resulted in lot's of functionality being duplicated in web-client. Also as the types keep on changing in the current early state of development this requires a lot of maintenance work.

To address these issues, there will be an SDK that will expose an API that allows the consumer to perform more complete workflows instead of just types and a few functions. This requires more work from the Namada core developers but will make the usage of Namada functionality more accessible. Namada CLI will also be a consumer of this client.

In its first stage, the SDK will be Rust only, but the web team should wrap their work as a TypeScript SDK and make it part of the SDK. At a later stage, more target platforms (Kotlin, Swift, ...) will be added. This web wrapper for the SDK will be called "Namada SDK - Web" in the tasks under this epic.

**Comment by jurevans** [comment]
Closing as not using epic, and SDK is implemented
