### ISSUE TITLE
Plan the refactor for using SDK

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#179]
Subtask of https://github.com/anoma/namada-interface/issues/177

Currently, the Web Clients Rust interface exposes something that will likely have to change when introducing the SDK to the front end. What has to change could be planned ahead of development for a better "big picture" view.

This would need the definitions or documentation of the SDK that is an outcome of https://github.com/anoma/namada-interface/issues/178

Outcome:
* Create specific tasks in GH for exposing the various parts of the SDK to the web consumer. At least split by:
  * accounts
  * balances
  * transfers
  * POS

**Comment by jurevans** [comment]
Closing as this is mostly implemented (no additional refactoring)
