### ISSUE TITLE
Basic implementation for integrating with extensions (Keplr, Metamask)

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#18]
# Description
This should likely be chopped down to smaller pieces based on https://github.com/anoma/namada-interface/issues/5

# Outcomes
* Create PRs for implementing basic functionality to initiate incoming transfers from Keplr and Metamask

**Comment by jurevans** [comment]
I've implemented a generic `Integrations` class in https://github.com/anoma/namada-interface/pull/153, which essentially achieves this. Each integration instance (Keplr, Anoma, etc.) is a class which implements the same interface, and in these classes we can have different implementations specific to the extension.

Another feature of this is that the accounts returned from Keplr can be mapped to our `Account` type, allowing the interface state to support it without additional logic. We would still need to implement logic specific to the extension for things like balance queries, but as far as the interface state is concerned, there should be no difference.

**Comment by jurevans** [comment]
Closed as basic implementation is complete
