### ISSUE TITLE
Change Namada Extension and Web Wallet to use SDK

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#181]
Subtask of https://github.com/anoma/namada-interface/issues/177

Once the "Namada SDK - Web" is in place. The client can be changed to use it. This should be done in several pieces as it will likely need substantial changes to the client. But this task could be used to create the first functionality using the SDK. But liekly best to split it a bit further to take care of different features split by at least these:

* accounts
* balances
* transfers
* POS

The concrete, more detailed tasks could be created as a result of this https://github.com/anoma/namada-interface/issues/179

**Comment by jurevans** [comment]
Closing as this is done
