### ISSUE TITLE
Implement the usage of Namada SDK for extracting details from existing blocks

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#186]
Subtask of https://github.com/anoma/namada-interface/issues/177

This is likely not to be used from the Extension/Wallet but has to be part of the "Namada SDK - Web". The data from the existing blocks have to be deserialised with the SDK. This functionality will be consumed by [Namada Block Explorer](https://namada.world/)

**Comment by jurevans** [comment]
We will need to revisit this and discuss with product
