### ISSUE TITLE
Create high quality documentation for the usage of the SDK

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#187]
Subtask of https://github.com/anoma/namada-interface/issues/177

When the initial implementation is completed and the team has done a couple of rounds of improvements, an easy to follow high quality documentation should be created and published.

This is rather a low-priority task for now and should only be done when the SDK is being implemented. There is a [task](https://github.com/anoma/namada-interface/issues/178) for more early-stage documentation and defining the specs and the APIs.

**Comment by jurevans** [comment]
Closing in favor of spec tasks (we can document our Rust SDK wrapper in specs)
