### ISSUE TITLE
Have E2E tests in place for functionality that will be impacted by the usage of the SDK

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#188]
Subtask of https://github.com/anoma/namada-interface/issues/177

The make the transfer to using SDK we should have higher test coverage in place to be able to be more confident when refactoring and changing the client.

We used to have E2E in place for part of the features using playwright, likely that can be used as a basis.

**Comment by jurevans** [comment]
Closing, as tests have been added
