### ISSUE TITLE
Refactor account types to one type

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#2]
# Description

When developing the MASP related features and needing a new type for shielded accounts, I wanted to keep the work as separate as possible. So I added:

```ts
type ShieldedAccount = DerivedAccount & {
  shieldedKeysAndPaymentAddress: ShieldedKeysAndPaymentAddress;
};
```
There should be no separate type for shielded and transparent accounts, the difference should be contained in the fields if the `Account`.

After this merge ensure that the features between shielded and transparent accounts in the UI are matching. 👇

<img width="400" alt="image" src="https://user-images.githubusercontent.com/2773320/177336940-4ba4d25f-74a1-4b05-b7a4-e300eb0da347.png">

This will affect various locations in the code where the accounts are being used. I introduced shielded accounts as a separate types as I wanted to keep the work as focused to adding MASP and not perform any refactoring in this.

# Outcomes
* a PR for implementing this

**Comment by jurevans** [comment]
This is completed
