### ISSUE TITLE
Address Audit Feedback

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#222]
Per audit from Least-Authority, we need to address a few items that were discovered.

Overview from findings:

### Critical

- Memory parameter of Argon2 is too low - Update defaults
  - Q: What should this be? Currently we use 4mib memory, this should at least be updated to 64
  - See <https://www.rfc-editor.org/rfc/rfc9106.html> for recommendations 
- Several Cases of Problematic Unused Code - This has mostly been addressed, but we need to compare our latest code with the commit that was audited
  - NOTE: `packages/utils/src/crypto` has been removed since audited commit
  - Remove unused code from the following: - **addressed in** #230
    - `packages/crypto/lib/src/utils.rs` 
    - `packages/crypto/lib/src/scrypt.rs` - **DONE**
    - `packages/crypto/lib/src/aead.rs` - will we be using this? If not, we should remove
- Seed Phrase Stored in Clipboard - Need more info

### Suggestions
- Use of insecure password is not enforced (**NOTE** This should be logged as a separate issue to discuss and implement)
  - It is recommended to use a library such as zxcvbn, as noted in [Wheeler16], or libpwquality to estimate the
strength of user-selected passwords, and requiring passwords to have the maximum strength of 4
- No option to change password: _TODO_ How will we implement this? Re-encrypt all stored values?
- No option to delete wallets: We should discuss how this will be done. Currently, the only way to delete a wallet is to remove the extension, which will purge all stored values. This should be a separate issue.
- Secrets Stored in Memory in Rust Code - It is recommended that we use the `zeroize` library to overwrite values in memory
- Insufficient Sanitization of Parameters - We don't use any functionality where this would be an issue, but properly sanitizing parameters should be in place.
- Add linting to the CI
- Ensure that all tests pass

Request access to https://github.com/LeastAuthority/namada-interface for review.

__TODO__ Log individual issues with details, assign priority

**Comment by emccorson** [comment]
Audit feedback PRs
---------------------------
[#234] - Issue A: Memory Parameter of Argon2 is Too Low
[#195] - Issue B: Several Cases of Problematic Unused Code
[#285] - Issue C: Seed Phrase Stored in Clipboard
[#235] - Issue D: Usage of Strong Passwords Not Enforced
[#277] - Issue E: No Option To Change User Passwords
[    ] - Issue F: No Option To Delete Wallets
[#257] - Issue G: Secrets Stored in Memory in Rust Code
[#260] - Issue H: Insufficient Sanitization of Parameters

**Comment by jurevans** [comment]
Closing this as all audit tasks have been addressed.
