### ISSUE TITLE
[Spike] Investigate improvements to error handling in Extension messaging

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#271]
The primary issue is that we get absolutely no useful errors when thrown within the messaging system in the extension. There's an additional issue is that we may not want to throw errors within the Requester for each failed message. As we're using `manifest v3`, we are forced to reckon with service worker shutdowns and restarts. 

It would maybe be best to move any `throw new Error` from within the Requester, and instead handle only where necessary. In order for the extension popup to _know_ that the service worker is available, we can make use of the `useUntil` hook and attemp to resolve a promise via the Requester (e.g., proceed when the a `requester.sendMessage` is able to resolve). See #270 where this is dealt with this way. The problem with this method is that any failed attempts to communicate with service worker will result in errors in the console that are not necessarily useful to the user.

It may be better if we're able to handle connection errors based on whether the promise is able to resolve, passing any Error object up to the client code to handle as needed (to determine if there actually is a critical failure that needs to be dealt with), instead of throwing an error within the service worker. on _any_ failed message. This would clean up logs in the console, and also give us a change to better handle errors and display useful information to the user.

**Comment by mateuszjasiuk** [comment]
Resolved!
