### ISSUE TITLE
UI Todos/Improvements

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#3]
# Description
This is for collecting UI related TODOs and improvement ideas in the app.

# Outcomes
* comments under this ticket listing the TODOs. When the work on them starts a new task should be created for each.

**Comment by memasdeligeorgakis** [comment]
It is just a placeholder so might not matter, but adjust the layout for mobile size, to not waste space

<img width="480" alt="image" src="https://user-images.githubusercontent.com/2773320/191051971-8e60d5b4-8650-45f4-99e8-16720a6b6114.png">

**Comment by memasdeligeorgakis** [comment]
Left align the breadcrumbs, as it looks a bit awkward like it is now (right chevron at center).
<img width="348" alt="image" src="https://user-images.githubusercontent.com/2773320/191056303-928dc0f2-f113-4734-9ae5-e337ab09b593.png">

**Comment by jurevans** [comment]
@memasdeligeorgakis I think we can probably close this issue, but I can leave it open for now in case we want to update it with recent issues.

**Comment by memasdeligeorgakis** [comment]
Improve the naming of `themeConfigurations` object in `DesignConfiguration`

**Comment by memasdeligeorgakis** [comment]
This component expects that the address is there. Otherwise crashes and the whole page does not render. It should work, but now this is coupled with and depending on the logic of whichever component is using this.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/2773320/203545871-f867bfe2-ee0e-4538-b328-c08ea5078d46.png">

**Comment by memasdeligeorgakis** [comment]
Let's alias the `string` or add a comment to inform what they represent.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/2773320/203548174-c28b1bbb-9158-4167-944b-97f72b06558b.png">

**Comment by memasdeligeorgakis** [comment]
rendering a whole object at token sending 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/2773320/206463077-c5479214-aaec-4419-acbd-3b837474eba5.png">

**Comment by memasdeligeorgakis** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/2773320/207804637-a2de8c97-a6a8-4416-ba96-cf9280c4c3c3.png">

Sizing/styling for this

**Comment by jurevans** [comment]
Closing, will address issues as they arise after implementing new designs
