### ISSUE TITLE
Pin Payment Addresses

### ISSUE THREAD

**Issue by mateuszjasiuk** [anoma/namada-interface#320]
As a user I want be able to pin the Payment Address to send pinned transfers to.

**PPA** - Pinned Payment Address

Case A - We allow only one transfer to PPA
Case B - We allow multiple transfers to PPA

- Upon address derivation user should be able to choose what kind of Payment Address they need(pin address toggle). After choosing the pinned option, user should either:
  - Case A - be warned that it's only for one time use(and potentially can sacrifice privacy)
  - Case B - be warned that using pinned address for multiple transfers might sacrifice the users privacy 

- In the list of addresses in the web interface we need to visually distinguish PPAs from regular ones, as `ppa` vs `pa` prefixes might not be obvious enough

- if the PPA was already used we want to either:
   - Case A - display information that this PPA was already used and every new transfer targeting it will be rejected by the VP
   - Case B - display information that this PPA was already used and using it multiple times might compromise the privacy

Things to consider:
- Should user be able to unpin the PPA and use it as a regular Payment Address?
- Should we only allow to pin the Payment Address upon address derivation?
- As a time of writing(Namada 0.17.5) it is possible to:
  - Create Payment Address **X**
  - Send transfer to **X**
  - Pin the **X** to create PPA called **PX**
  - Send transfer to **PX**
  In this case how should we display addresses(and balances) in the web interface as they are related and share the balance?

**Comment by cwgoes** [comment]
I recommend that we support pinned payment addresses, but that we - by default - only display _unused_ ones. The user should think of pinned addresses like something that they create and can use once but then go away (and they need a new one). In some advanced mode we can show the old ones, but I think they should be hidden by default.
