### ISSUE TITLE
Calculate Gas Fees & Specify Gas in Interface

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#378]
Currently, the interface does not account for gas fees when validating tx amounts. This obviously creates issues when a user wants to use 100% of available funds, which will fail as there will be insufficient fees.

- [ ] Interface should calculate gas fees and provide that when validating transaction amounts (e.g., `Estimated gas = ...`)
- [ ] We have UI for Low/Medium/High gas usage, but these currently do nothing:
  - [ ] We need to specify values for these (for both Testnet and Mainnet - this may take some research to determine what the values should be, and testnet gas may just be a constant we set, whereas mainnet would need to be calculated)
  - [ ] Look into implementing token for paying gas fees - this would effect the `TxArgs` (which I believe are currently hardwired to NAM)
- [ ] Perhaps as a part of this issue, we allow user to specify `gas_payer` account as well, but we could also address that in a separate issue once it's better understood

**NOTE** Currently, the transaction gets built inside the injected content scripts from args passed from the interface, which means we have to specify gas in the interface (currently only displays on the transfer view). Maybe it should be constructed in the extension, and gas set in the approval pop-up? Not sure about that, maybe that's a product question, but if we leave it in the interface, gas would need to be able to be specified on all tx, like IBC, Bridge, and Staking

**Comment by emccorson** [comment]
Resolved by #576.
