### ISSUE TITLE
Generic Todos/Improvements

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#4]
# Description
This is for collecting generic TODOs and improvement ideas in the codebase.

# Outcomes
* comments under this ticket listing the TODOs. When the work on them starts a new task should be created for each.

**Comment by memasdeligeorgakis** [comment]
Move all accounts state management to the directory that is currently being called `AccountsNew`.

**Comment by memasdeligeorgakis** [comment]
Think about the folder/component hierarchy and structure:

```bash
/App
  /StakingAndGovernance
  # 👆 only this is accessing the state management
  /Staking
    /StakingOverview
    /ValidatorDetails
    /NewStakingPosition
    # 👆 we need a type there that is re-imported from `/Apps/StakingAndGovernance` 
    # and defined in `/slices/StakingAndGovernance`
/slices
  /StakingAndGovernance
  # the state management stuff could well live next to the main consumer
  # to be more "contained"    
```

**Comment by memasdeligeorgakis** [comment]
Create proper validation utils '(as part of `<Input />`, likely the best)

**Comment by memasdeligeorgakis** [comment]
Thinking about the naming of the shared packages

```bash
/packages
  /components # ui-components
  /crypto # if this is purely some abstract utils, could it live under utils?
  /integrations # external-wallet-intergrations
  /masp-web # likely this could move to live under the directory containing other namada specific functionality
  /rpc # networking this is to abstract communication, not rpc protocol
  /seed-management
  /session # wallet-session
  /shared #namada-shared and do we need this independently are we using this directly from our ts code?
  /storage
  /tx # this would be covered by the one wrapping namadas core types?
  /types # would these not be shared from the directory containing the actual functionality for these types
  /utils
  /wallet # would this functionality live in location managing the keys 
  /wasm # namada-shared
```

**Comment by memasdeligeorgakis** [comment]
Check out the generics in `KVStore` 
```ts
// namada-interface/packages/storage/src/store/types.ts

// from
export interface KVStore {
  get<T = unknown>(key: string): Promise<T | undefined>;
  set<T = unknown>(key: string, data: T | null): Promise<void>;
  prefix(): string;
}

// to aligned
export interface KVStore<T> {
  get(key: string): Promise<T | undefined>;
  set(key: string, data: T | null): Promise<void>;
  prefix(): string;
}
```
https://github.com/anoma/namada-interface/pull/97#issuecomment-1277650205

**Comment by memasdeligeorgakis** [comment]
`T` should likely enforce `{id: string}` as it is very likely is expected to be present as expected in `update` and `remove`.
```ts
// namada-interface/apps/extension/src/background/types/Store.ts
export interface IStore<T> {
  set(state: T[]): Promise<void>;
  get(): Promise<T[]>;
  append(state: T): Promise<void>;
  update(id: string, state: Partial<T>): Promise<void>;
  remove(id: string): Promise<void>;
}
```

**Comment by memasdeligeorgakis** [comment]
Document the issue, investigate and find a fix/workaround.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/2773320/195821569-7b9ee13e-2e30-4243-a2d5-bd2db831719d.png">

**Comment by memasdeligeorgakis** [comment]
This is being used in the case where we query the return value from the check whether a Tx was applied successfully to a block. Maybe we can define a more specific type.

We used to get the result for this call in clear call, but after stopping using WebSocket we are querying this from the storage path and getting it in Borsh encoded format. So once we want to utilise that data we anyway need the type definitions.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/2773320/206502565-eeaef138-76c6-4dc7-89a3-69aee50d9e90.png">

<img width="537" alt="image" src="https://user-images.githubusercontent.com/2773320/206504707-d60c7336-0568-478a-899f-99ae46c205f0.png">

**Comment by jurevans** [comment]
Closing, will address issues as they arise after implementing new designs
