### ISSUE TITLE
Staking UI Improvements

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#420]
This issue is to track a few UI/UX improvements to the Staking page.

- [ ] Remove temporary placeholder data (as it is confusing)
- [ ] Remove unused links (see tabs under staking, two of these don't go anywhere, so we should remove them until we perhaps have a use for something like that)
- [ ] Display more of the user's address in `My Staking` (under `Validator Details`)
- [ ] Layout search filter & pagination better
- [ ] Hide pagination bar if results < `ITEMS_PER_PAGE`
- [ ] Should user be able to select between different `ITEMS_PER_PAGE`s (e.g., instead of a single constant, have 3 option dropdown menu, like 10/25/50 or 10/15/25, though 50 may be high considering we need to fetch bonds for each address displayed, but something like that)? This isn't critical, just something we could do.
- [ ] "My Validators" maybe needs to be paginated as well
- [ ] Update `Table` component to display message if no results are provided (maybe a prop can determine what is displayed here?)
- [ ] This is picky, but we should either 1) Hide the `next` or `previous` buttons if they are disabled, or 2) make it very obvious that they are disabled, and remove the pointer cursor for those classes. See https://github.com/AdeleD/react-paginate for more info

**Comment by mateuszjasiuk** [comment]
Waiting for new designs
