### ISSUE TITLE
Staking, Governance, Public Goods Funding

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#43]
# Description
This contains all the functionality for Staking, Governance, and Public Goods Funding (PGF).

# The following features are required:
* All management of staking (changing positions, displaying existing positions, ...)
* Creating new governance proposals
* Voting on existing governance proposals
* Viewing of public goods funding

# Designs & Resources
The initial description of the UIs in the previous wireframes
https://specs.anoma.net/main/architecture/clients/web-wallet.html#stakinggovernancepgf

Additional and the to-be-used design work for the Staking, Governance and PGF
https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?node-id=9219%3A15770

Namada Code
[documentation/dev/src/explore/design/ledger/pos-integration.md](https://github.com/anoma/namada/blob/242f1e483725735db76cf61c40f312cfd62d1b3d/documentation/dev/src/explore/design/ledger/pos-integration.md)

**Comment by jurevans** [comment]
Closing, will add tasks and update as necessary when we receive designs
