### ISSUE TITLE
Extension - Incorporate changes to address

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#438]
We need to test extension against https://github.com/anoma/namada/pull/2060 (`tiago/new-addresses`) and ensure that we are getting the correct addresses/prefixes.

- [x] Point to `tiago/new-addresses` and update as necessary
- [x] Fix unit tests to reflect these changes

TODO: Follow up with:
- [x] Get these changes merged into https://github.com/anoma/namada-interface/pull/431

**Comment by emccorson** [comment]
Merged into #431!
