### ISSUE TITLE
Extension UI updates 2.0

### ISSUE THREAD

**Issue by ChrisHoltDesign** [anoma/namada-interface#477]
UI Fixes
- [ ] When copy to clipboard is selected we need a prompt to tell the user its is successful 
- [ ] On firefox the extension window opens very very wide
- [ ] We need to prompt for when the user changes their password so they know it is successful
- [ ] Check rounding of box edge consistency
- [ ] View seed phrase warning box can we expand the text box so "anyone" fits on the same line and or make the yellow text 13px
- [ ] Animation on the lock 

Features
- [ ] Do we need a maximum number of password input attempts before the user has to reset the extension and use the seed phrase
- [ ] Add in forgot password message that links to FAQ telling to re-install the extension. Could this be on discord for now?

**Comment by ChrisHoltDesign** [comment]
- [ ] If you click connect to ledger without a device attached you get the warning box. However if you then connect a ledger the warning box still stays on screen even though you have proceeded to step 2
<img width="581" alt="Screenshot 2023-11-28 at 13 26 25" src="https://github.com/anoma/namada-interface/assets/95826854/4e610dbf-5020-45c6-b3aa-816f553312f7">

**Comment by emccorson** [comment]
- [ ] After pasting a 24 word seed phrase, the "12 words" radio button is still selected.

**Comment by mateuszjasiuk** [comment]
Completed!
