### ISSUE TITLE
bug: Extension - Fix issues with connections

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#480]
This issue is to implement fixes for the following:

- [ ] Extension fails to connect to interface and allow approvals when no accounts have been created - this should fix that
- [ ] Don't require a chain ID in order to connect - the extension will currently fail to connect if there is a mismatch between the chain ID and the interface during build - this should not prevent interfaces from connecting

**Comment by promisegraph** [comment]
**Promise Graph Bot** < last updated: Mon, 27 Nov 2023 14:39:38 GMT >

*Parsing results*

Error: 0: instance.state is not one of enum values: Unplanned,InPlanning,Planned,InProgress,InReview,Done,Cancelled
