### ISSUE TITLE
Staking, Governance, Public Goods Funding - Governance View

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#51]
This is for developing the Staking view as displayed in [Figma](https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?node-id=9296%3A13063). This will require:

* setting up the state management for Governance
* creating a mock util for fetching staking-related data

**Comment by jurevans** [comment]
Closing, as we will create and delegate tasks once we have new designs to work with
