### ISSUE TITLE
Staking, Governance, Public Goods Funding - Public Goods Funding View

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#52]
This is for developing the Staking view as displayed in [Figma](https://www.figma.com/file/aiWZpaXjPLW6fDjE7dpFaU/Projects-2021?node-id=9254%3A14841). This will require:

* setting up the state management for Staking
* creating a mock util for fetching staking-related data

**Comment by jurevans** [comment]
Closing, as we will create tasks and delegate as needed once we have new designs
