### ISSUE TITLE
Figure out webpack bundle names to prevent caching issues

### ISSUE THREAD

**Issue by mateuszjasiuk** [anoma/namada-interface#556]
Right now we produce bundles which look like this:
``` 
filename: "[name].bundle.js",
```
Which might lead to cache issues(I think mostly for namada interface).
Using default hashing mehod will not work with `wasm-bindgen-rayon`.
We could use sth like this:
```
    filename: (pathData) =>
      `${pathData.chunk.name}.${process.env.npm_package_version}.js`,
```
or some other hashing mechanizm.

**Comment by jurevans** [comment]
Closing, as we're moving away from webpack for the interface
