### ISSUE TITLE
[SPIKE] Inquire into us using AWS for deployment

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#560]
We should look into the possibility of using AWS for deployment, i.e., could the interface team have a set of permissions to do this on our own?

- Ask Gianmarco
- Will Cloudfront be used for geo-blocking?
- etc.

**Comment by pedrorezende** [comment]
@jurevans can we close this issue?

**Comment by pedrorezende** [comment]
Closing because we won't host anything
