### ISSUE TITLE
BUG: Interface: Proposal queries are failing on namada.me

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#595]
At https://namada.me, navigating to the `Proposals` page results in the following error:

```
data:application/was…NpZ24tZXh0:0x30a1e2 Uncaught (in promise) RuntimeError: unreachable
    at data:application/was…NpZ24tZXh0:0x30a1e2
    at data:application/was…NpZ24tZXh0:0x333e65
    at data:application/was…NpZ24tZXh0:0x31f560
    at data:application/was…HNpZ24tZXh0:0x94c52
    at data:application/was…NpZ24tZXh0:0x2bcd63
    at data:application/was…NpZ24tZXh0:0x33ab20
    at __wbg_adapter_36 (shared.js:229:1)
    at real (shared.js:196:1)
```

As such, no proposal data is loaded and displayed. We may need to make changes to `Query` in `@namada/shared`, but this also could be an interface-side issue - needs to be investigated.

**Comment by phy-chain** [comment]
@jurevans Did you make any progress on this ?
Im getting a similar issue when executing another wasm, and it's kind of difficult to debug :sweat_smile:

**Comment by mateuszjasiuk** [comment]
It should be fixed by using an Indexer to query proposals later.
