### ISSUE TITLE
Shared package issue. Module not found: Can't resolve 'wbg'

### ISSUE THREAD

**Issue by Romainua** [anoma/namada-interface#601]
**System**
- Mac OS
- next js 14.1.0

next config
```
const nextConfig = {
  webpack: (config) => {
    config.experiments = {
      asyncWebAssembly: true,
      layers: true,
    }
    config.module.rules.push({
      test: /\.wasm$/,
      type: 'webassembly/async',
    })
    return config
  },
}
```
Have got an error when call `initShared()` from `import { init as initShared } from '@namada/shared/src/init-inline'`
Error: `Module not found: Can't resolve 'wbg'`

**Comment by Romainua** [comment]
@jurevans could you help here?

**Comment by emccorson** [comment]
That import statement doesn't look quite right. On the latest version of @namada/shared on npm, there is no `src` directory, only `dist`. I think your import statement should be:

```
import { init as initShared } from "@namada/shared";
```

Can you try that and let us know if it works please? Also make sure that you are using the latest version of @namada/shared from npm, or you are using something different for some reason just let us know.

I actually ran into a new import problem after trying that, but I'm not sure if it is just local to me. But in any case, this should be the correct import statement.
