### ISSUE TITLE
Faucet updates for SE

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#607]
Amendments:
- Update favicon
- Change url to [namada.net/shielded-expedition/faucet](http://namada.net/shielded-expedition/faucet)

Text:
- Namada Faucet --> Namada Shielded Expedition Faucet
- What’s the “Target address”?
- Token address (defaults to NAM) --> “Enter your Namada address (tnam1)”

**Comment by mateuszjasiuk** [comment]
Done!
