### ISSUE TITLE
Extension connected sites UI doesn't show remove button

### ISSUE THREAD

**Issue by emccorson** [anoma/namada-interface#633]
The list of connected sites in the extension has a remove button beside each list item, but the icon doesn't show so it's not clear there is a button there.

I'm wondering if the list still has the temporary styling that I originally did and wasn't changed in the extension UI overhaul.

![2024-02-15-080200_383x320_scrot](https://github.com/anoma/namada-interface/assets/13696952/9c7bb06a-5d05-4f7e-a308-93116928fb65)

**Comment by mateuszjasiuk** [comment]
Done!
