### ISSUE TITLE
Loading shielded context takes too long time on SE

### ISSUE THREAD

**Issue by TuanTQ15** [anoma/namada-interface#663]

**Comment by pnam1609** [comment]
Too long for load block to shielded context and scaning. In SE have more than 120k block. It take maybe 3 - 4 days for fetching block and whenever rpc is or some thing is failed, it make function break. And we need load shielded context again.

**Comment by pnam1609** [comment]
Take a long time to shieled sync. Who one need use shieled action.

**Comment by mateuszjasiuk** [comment]
Duplicate of #662
