### ISSUE TITLE
Extension: Add select fiat currency to settings

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#675]
- User should be able to select their currency, and have the conversion rate applied to token balance

Figma designs:
https://www.figma.com/file/NFyHbLZXBSl3aUsMxtffvV/Namada-End-User-Interface-V1.0-%2F-Phase-1%3A-Block-Party?type=design&node-id=3968-2&mode=design&t=mWoF2N3EVo2YwmLj-0

**Comment by emccorson** [comment]
Probably needs to be done after #674.

**Comment by emccorson** [comment]
Won't be done now that requirements have changed.
