### ISSUE TITLE
"Click to download the extension" button redirects to namada.me

### ISSUE THREAD

**Issue by honeygoyal120** [anoma/namada-interface#683]
##  The button "Click to download the extension" is redirecting to namada.me only. It isn't opening the extensions store as intended.
<img width="1680" alt="Screenshot 2024-03-23 at 2 52 00 PM" src="https://github.com/anoma/namada-interface/assets/147941656/649a6333-b1bd-4c77-9e4f-757e20a828e4">

## The following code needs to be updated
<img width="1186" alt="Screenshot 2024-03-23 at 3 14 53 PM" src="https://github.com/anoma/namada-interface/assets/147941656/7137c52f-877d-493c-961b-dbe7c337006b">
<img width="1220" alt="Screenshot 2024-03-23 at 3 15 59 PM" src="https://github.com/anoma/namada-interface/assets/147941656/0c577799-b8f6-4d3b-9ed7-5cacc6dd48e4">

### Please suggest the required changes, I'll update the code accordingly.

**Comment by mateuszjasiuk** [comment]
Closing this for now as UI is in the middle of rework :)
