### ISSUE TITLE
Faucet API is non functional

### ISSUE THREAD

**Issue by givingmittal** [anoma/namada-interface#684]
The <b>https://faucet.api.heliax.click/shielded-expedition.88f17d1d14/api/v1/faucet/setting</b> endpoint of faucet api is giving 408/502. Kindly check. Adding some screenshots below.
<img width="1003" alt="Screenshot 2024-03-24 at 3 39 23 AM" src="https://github.com/anoma/namada-interface/assets/148149300/78d9c5ed-32c4-4631-9e97-f1073dcf8bbe">
<img width="915" alt="Screenshot 2024-03-24 at 3 39 39 AM" src="https://github.com/anoma/namada-interface/assets/148149300/5d2c9e5c-95cc-49fe-8f00-690527b0135a">

**Comment by mateuszjasiuk** [comment]
@givingmittal So https://faucet.api.heliax.click/shielded-expedition.88f17d1d14/api/v1/faucet/setting api is working fine. Limit is set to 10nam per request every 6h

**Comment by givingmittal** [comment]
@mateuszjasiuk I get this error as soon as I connect my wallet extension. The settings api gives 408/502. Is it working for you?

**Comment by mateuszjasiuk** [comment]
@givingmittal it looks like a cors issue. I will let you know once it's resolved!

**Comment by mateuszjasiuk** [comment]
@givingmittal looks like it's working again!
