### ISSUE TITLE
It is not possible to set memo field for IBC Transfers (`@namada/types`)

### ISSUE THREAD

**Issue by hkey0** [anoma/namada-interface#689]
Hello,
I have been tinkering with `namada-interface` for a long time. I want to add memo fields to IBC transfers to build an app that supports Shielded Swap, but this is not possible. I think this is due to `@namada/types`. 

By the way, the memo field I am talking about here is the memo field for the IBC transfer to the destination network, not for the namada transfer, the two are separated.

No IBC object in Namada types supports memo:
https://github.com/anoma/namada-interface/blob/1e07a10531bc1852c6a19376bb4cd5de10c265c6/packages/types/src/tx/schema/ibcTransfer.ts#L7-L35

I'm not sure if this is the problem, but we need this feature. Have a nice day guys!

**Comment by bernatfp** [comment]
I was going to report the same issue. I included more details in this gist: https://gist.github.com/bernatfp/65a3ededc00668802929466b0294bf7c

**Comment by hkey0** [comment]
Hi @mateuszjasiuk ,
When is this feature expected to be added? I need it for the Shielded Expedition.
Thanks!

**Comment by mateuszjasiuk** [comment]
@bernatfp @hkey0 
https://github.com/anoma/namada-interface/pull/692
I'm not exactly sure when it will be published, but you can build extension from source if you are in hurry.

You should be bale to test it through interface or just by calling sth like:

```ts
 await namada.getSigner().submitIbcTransfer(
   {"source":"tnam1qqshvryx9pngpk7mmzpzkjkm6klelgusuvmkc0uz","receiver":"cosmos1sy99khct7t7wth2wus5xpwkcf6n8p0lvtgaff9","token":"tnam1qxgfw7myv4dh0qna4hq0xdg6lx77fzl7dcem8h7e","amount":"123","portId":"transfer","channelId":"some-channel", "memo":"some-memo"},
   {"token":"tnam1qxgfw7myv4dh0qna4hq0xdg6lx77fzl7dcem8h7e","feeAmount":"0","gasLimit":"20000","publicKey":"tpknam1qzz3nvg5zjwdpk5z0x9ngkf7guv9qpqrtz0da7weenwl5766pkkgvvt689t","chainId":"localnet.a38cf62f63db8c1a1f3c9"},
   "mnemonic"
 );
```

**Comment by hkey0** [comment]
Working, thanks!
