### ISSUE TITLE
IBC Transfers not possible

### ISSUE THREAD

**Issue by bernatfp** [anoma/namada-interface#690]
I have been unable to get IBC transfers to work with the namada interface, whether through namada.me or locally. 

I added some logs around the execution flow to see where the error occurs, and it seems like the chrome extension is complaining about the `token` field being null, which I don't understand because it seems correctly populated before `integration.submitBridgeTransfer` is invoked.

This is what I see in my browser's developer console:

<img width="1027" alt="Screenshot 2024-03-26 at 22 11 55" src="https://github.com/anoma/namada-interface/assets/565238/83c85c89-783e-40b9-b0d9-8196aafbda5f">

I am on the latest version of the frontend. The browser extension is the live one on the Chrome web store.

**Comment by emccorson** [comment]
Thank you for the report!

As far as I know, we are releasing a new version of the extension in the Chrome web store very soon.

The current interface is basically a prototype and we are currently in the process of replacing it. If something is not working in the interface, that's expected and we will be dealing with it very soon.

I will close this for now.
