### ISSUE TITLE
Issue with IBC transfer from Cosmos to Namada

### ISSUE THREAD

**Issue by duyhla** [anoma/namada-interface#702]
# Bug 1: Unable to retrieve minDenom when performing IBC transfer from Cosmos to Namada.

When I perform an IBC transfer from a Cosmos account to a Namada account, I encounter an issue with retrieving the minDenom value. The expected behavior is to retrieve the minDenom value to ensure consistency among currency units in the system, but currently, this value is not returned correctly.

# Bug 2: Failure to convert from Atom to uAtom when creating an IBC transfer, while the transfer unit is currently set to uAtom.

When initiating the creation of an IBC transfer, the system should convert the quantity of Atoms into uAtoms to ensure consistency in the transfer process. However, despite the expected conversion, Atoms are not being converted to uAtoms during the creation of the IBC transfer. Furthermore, it's noteworthy that the current transfer unit is set to uAtom.

# Proposed Solution:
I have already created a pull request (PR) #703  to fix both bugs. The proposed solution involves implementing the following:

Implementing error handling mechanisms to ensure proper retrieval of minDenom during IBC transfer from Cosmos to Namada.
Introducing conversion logic to automatically convert Atoms to uAtoms when creating an IBC transfer.

**Comment by danhnguyen1-tiki** [comment]
I think @emccorson can help you

**Comment by jurevans** [comment]
@duyhla hello! We're closing this issue as this is being handled in another issue. Thanks!
