### ISSUE TITLE
Incompatibility Issue with Memo Length Between ibc-gen-shielded and namada-interface client (Stargateclient)

### ISSUE THREAD

**Issue by duyhla** [anoma/namada-interface#704]
# Description:
Currently, ibc-gen-shielded is utilized to generate memo with a maximum length of 2543 characters. However, namada-interface client (Stargateclient) and Cosmos only accept memo lengths of up to 512 characters. This disparity in memo length compatibility impedes the generation of memos in ibc-gen-shielded that are compatible with the receiving systems.

# Expected Behavior:
ibc-gen-shielded should generate memo within the length limit supported by namada-interface client and Cosmos, ensuring compatibility and seamless transmission of memo between systems.

**Comment by danhnguyen1-tiki** [comment]
You need to tag someone @mateuszjasiuk

**Comment by mateuszjasiuk** [comment]
Hello! Thank you for adding an issue. I will close this in favor of #714. If you have any questions ask them there :)
