### ISSUE TITLE
Enhancement: Saving latest block for next shielded sync query

### ISSUE THREAD

**Issue by huvny-de** [anoma/namada-interface#715]
### Issue:
- In version 0.32.0 Namada SDK, there is a feature to apply for passing 2 attributes start_query_height and last_query_height. It only helps to fetch and scan in specific range of block to optimize shielded sync time.
- For latest code namada-interface doesn't using that. So when shielded sync still need fetching still have to call the API to fetch redundant blocks
![image](https://github.com/anoma/namada-interface/assets/75641149/9f6f9d51-52d6-46bc-b09b-0461576eaa58)

**Comment by mateuszjasiuk** [comment]
@huvny-de Hello :wave:, we are aware of this change. I will close this one in favor of https://github.com/anoma/namada-interface/issues/662,, you can keep track of discussion there
