### ISSUE TITLE
Issue with notification when IBC transfer from Cosmos to Namada

### ISSUE THREAD

**Issue by Piedmon** [anoma/namada-interface#726]
## When IBC transfer from Cosmos to Namada don't have any notification.
When transferring IBC from Cosmos to Namada, there is no notification to inform the user whether the transaction is being processed or not. This creates difficulty for users.

## Proposed Solution:
I have already created a pull request (PR) https://github.com/anoma/namada-interface/pull/725 to improve UX/UI. The proposed solution involves implementing the following:
Implementing an event listener to capture events when a user submits an IBC transfer from Cosmos to Namada.
Display a notification when the transaction is successfully sent using the Keplr wallet.

**Comment by Piedmon** [comment]
@emccorson @mateuszjasiuk Hopefully, you guys can review my submission soon, Thank you so much.

**Comment by jurevans** [comment]
@Piedmon hello! We're closing this issue as this is currently being implemented for IBC in Namadillo. Thanks!
