### ISSUE TITLE
In toast notification don't display transaction hash when successfully

### ISSUE THREAD

**Issue by TuanTQ15** [anoma/namada-interface#729]
## Problem
- In toast notification should display transaction hash when successfully
- Also when click transaction hash in notification should be redirect to explorer to improve user experience

**Comment by Piedmon** [comment]
Duplicated issue: https://github.com/anoma/namada-interface/issues/726. You could discuss on this link to fix both.

**Comment by mateuszjasiuk** [comment]
As I mentioned in the related PR. All the changes(especially in the UI) should be discussed first in the issue and then worked on. There reason is that we might not want to introduce particular UI change or UI is being reworked already(as in this case). :(
