### ISSUE TITLE
Staking, Governance, Public Goods Funding - Modal Component for Staking/Unstaking

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#73]
# Description

Add a modal component, it should have the following features:
- should be able to trigger from the actions
- should be able close from the actions
- should have a configurable title
- should have a dismissing button
- should allow user to close by clicking outside (in the overlay sections)

As we have are not using Storybook yet, just directly implement it for the use case of staking/unstaking in the validator details view.

**Comment by memasdeligeorgakis** [comment]
Instead of doing this properly in isolation, I just decided to do it directly in the first use case. The designs/specs if might change when we get the proper designs, so this is just like MVP for modals.

**Comment by mateuszjasiuk** [comment]
Closing as we already have a modal component!
