### ISSUE TITLE
All Bug and issue related shielded action

### ISSUE THREAD

**Issue by pnam1609** [anoma/namada-interface#733]
### Bug 1: Wrong chain id passing for shielded ibc transfer ( only ibc shielded )
![image](https://github.com/anoma/namada-interface/assets/44290296/729f0479-e283-4524-889c-3ff31a3406b5)

### Bug 2: Private key is not passing into shielded action ( both ibc shielded and internal shielded transfer )
![image](https://github.com/anoma/namada-interface/assets/44290296/b4b91e34-65b6-4d10-ab9b-4216b4205ca4)

### Bug 3: Public key is missing in txArgs when execute shielded transfer ( both ibc shielded and internal shielded transfer )
![image](https://github.com/anoma/namada-interface/assets/44290296/14ef7b9a-eee2-4160-834f-df225fa6fa17)
Note: Relate this bug, even though an error occurred, the transaction was still successful

### Bug 4: disposable_signing_key should be false when using shielded transfer ( only internal shielded transfer )
![image](https://github.com/anoma/namada-interface/assets/44290296/6c51b735-9ccc-4990-93ca-1fd51d80453e)

**Comment by pnam1609** [comment]
I build the extension using the SDK, this is the problem I remember. Some bug I've forgotten

**Comment by jurevans** [comment]
Shielded actions over IBC is not yet supported by extension
