### ISSUE TITLE
Interface: Implement staking rewards

### ISSUE THREAD

**Issue by emccorson** [anoma/namada-interface#741]
Update interface to support querying and claiming rewards.

Claiming rewards is already supported in the SDK.

Figma designs:

https://www.figma.com/file/NFyHbLZXBSl3aUsMxtffvV/Namada-End-User-Interface-V1.0-%2F-Phase-1%3A-Block-Party?type=design&node-id=3968-2&mode=design&t=mWoF2N3EVo2YwmLj-0

**Comment by jurevans** [comment]
Closed as finished!
