### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#75]
# Description
The key management should be done in an extension to allow 3rd party applications to use transactions signing of Namada.

# The following features are required:
* Should be in a browser extension
* Should allow all management of accounts
* Should allow re-generating accounts from the seed phrase
* Should allow re-displaying and exporting of the seed phrase
* Should expose a well-documented API through the `window` object

# Designs & Resources
TBD

**Comment by jurevans** [comment]
Closing, as we're not using epics
