### ISSUE TITLE
MASP

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#76]
# Description
The Multi Shielded Assets Pool is the way for Namada to allow shielded transfers. It is heavily dependent on functionality contained in the MASP repository. The challenge is to make it performs well enough from the UX point of view on low-powered devices behind poor internet connections and restricted data usage limits.

# The following features are required:
* Functioning generation of shielded transactions (transfers)
* Make it usable in low powered android devices
* Optimise to prevent excessive data fetching (nice to have for 1.0)
* Reuse code in a sustainable way (nice to have 1.0)

# Designs & Resources
* MASP repository - https://github.com/anoma/masp
* Sapling paper - MASP is based on Sapling, https://github.com/zcash/zips/blob/main/protocol/sapling.pdf

**Comment by jurevans** [comment]
Closing, as we're not using epics
