### ISSUE TITLE
Errors in shared are not caught properly

### ISSUE THREAD

**Issue by emccorson** [anoma/namada-interface#783]
In the function `promiseWithTimeout` the line `const res = await fn(...args);` doesn't handle cases where the Promise is rejected. This means the caller can't catch the error and it ends up being printed to the browser console.

First we need to check if this function is still needed. I think it was originally written to deal with Rust panics in the Namada SDK, but there was work done to remove the panics so it might not be needed anymore.

**Comment by jurevans** [comment]
Closing this issue
