### ISSUE TITLE
useExtensionConnect hook doesn't react to connection being revoked

### ISSUE THREAD

**Issue by emccorson** [anoma/namada-interface#796]
When using the useExtensionConnect hook, the returned connection status doesn't get updated when the namadaExtensionConnectedAtom is updated.

I would vote for having a single source of truth for the extension's connection status instead of using both namadaExtensionConnectedAtom and connectionStatus. Otherwise, the connection code in other places can get a bit complicated.

It might be that the type of namadaExtensionConnectedAtom should change to the ConnectStatus type instead of boolean. And then you could do useAtomValue(namadaExtensionConnectedAtom) in TopNavigation to get the same effect (or just returning extensionConnected from this hook might be fine too).

**Comment by pedrorezende** [comment]
Fixed on #856
