### ISSUE TITLE
Notification system for the UI

### ISSUE THREAD

**Issue by memasdeligeorgakis** [anoma/namada-interface#8]
# Description
The app needs a notification mechanism. It should have the following features:
* can add multiple notification simultaneously
* user can dismiss them
* can have info/warning/error
* can contain child component at init to freely be customisable
* can be initiated from actions
* can be dismissed from actions and components

# Outcomes
* a PR for implementing this

**Comment by jurevans** [comment]
Closing as we have implemented toast notifications.
