### ISSUE TITLE
Responsive issues + Impliment the mobile send to desktop screens

### ISSUE THREAD

**Issue by ChrisHoltDesign** [anoma/namada-interface#828]
Can we tidy up the very small desktop screens for if the user minimises.

<img width="923" alt="Screenshot 2024-06-02 at 10 01 45" src="https://github.com/anoma/namada-interface/assets/95826854/646b3cb3-480e-41d9-840b-e25be86f698c">

+ Add the mobile send to desktop screen.

<img width="685" alt="Screenshot 2024-06-02 at 10 00 54" src="https://github.com/anoma/namada-interface/assets/95826854/95730586-9094-4cc9-b2b4-df416088b6ab">

**Comment by pedrorezende** [comment]
Fixed on #473
