### ISSUE TITLE
Left panel should be sticky inside the browser window

### ISSUE THREAD

**Issue by ChrisHoltDesign** [anoma/namada-interface#834]
<img width="1792" alt="Screenshot 2024-06-03 at 15 20 04" src="https://github.com/anoma/namada-interface/assets/95826854/8f0c4986-f5c3-4721-b1fd-9d0ebe90c112">

Currently there is a small scroll meanign we don't see the social icons on the Nav side bar. 

-Could we lock that to the browser height 

- Would be nice on the overview screen to not have a scroll on any elements. (for this phase)

**Comment by emccorson** [comment]
Done
