### ISSUE TITLE
Extension: Display Tx details in Approval window for signing

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#835]
We need to re-introduce details about the Tx being signed in the Approval views.

- Extension will at the very least know what _type_ of Tx is being signed for display purposes
- Add a query to obtain Tx details from the `PendingTx`
- Currently, extension receives serialized values for `tx` & `signing` data as constructed by `build` functions in the SDK. Is it possible to deserialize the Tx completely within the extension from `tx` solely?
- Alternatively, we can pass the original Tx constructing args to this call to make them available to the extension, though if we can avoid that, we probably should, just to keep the API as simple as possible
- Whichever values will be required should be wrapped in the type returned by the SDK JS package's `buildTx` functions, for simplicity's-sake. The TxType can be appended to the route used to invoke the approval, so we can use the `enum` value, e.g.: `/approve-sign-tx/1/....` where `1` references the enum value, or `/approve-sign-tx/transfer/...`

The route could simply follow this structure:

```
/approve-sign-tx/{accountType}/{txType}/{msgId}
```

Where `accountType` determines whether we use Extension key store, or Ledger HW Wallet, and `txType` tells us how to deserialize & display the Tx, and `msgId` gives us the key for the `PendingTx`

See Figma designs for Tx approvals:
https://www.figma.com/design/NFyHbLZXBSl3aUsMxtffvV/Namada-End-User-Interface-V1.0-%2F-Phase-1%3A-Block-Party?node-id=4285-26253&t=k9h95cJpkjsPAh8e-0

## Sign Arbitrary

We should handle "details" the same way when signing arbitrary data as well. We query the details for `signArbitrary` calls, which will always return a string. Then, attempt to parse the string as JSON, and format, something like:

```
try {
  const json = JSON.parse(data);
  const formatted = JSON.stringify(data, null, 2);
  setData(formatted);
} catch (e) {
  setData(data); // unchanged
}
```

And display in a `<pre></pre>` per the designs

Figma:
https://www.figma.com/design/NFyHbLZXBSl3aUsMxtffvV/Namada-End-User-Interface-V1.0-%2F-Phase-1%3A-Block-Party?node-id=3968-2&t=da4IZ3LoUqFISuyV-0#812357271

**Comment by ChrisHoltDesign** [comment]
I've updated the UI slightly removing the Fee and memo from that design specific design

If we can get is as close to this as possible then great :)

Might need a horizontal scroll on each of the list items if we have to display a full address + a large amount or denomination of NAM
