### ISSUE TITLE
Accounts - Restoration and Export

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#9]
This issue is composed of three main parts:

1. Restore accounts from Mnemonic
2. Export wallet state to JSON file
3. Import/restore wallet state from JSON file

### Restore from Mnemonic:
Restoring an account from a mnemonic will involve looking up established addresses on the ledger. I will have to check with the ledger team to determine exactly how this should be done, but I assume we will be establishing a root / extended key from the mnemonic, then we will derive keys from the mnemonic and query the ledger for any existing balances in storage.

### Export wallet state
The user should be able to export all of their data to an unencrypted JSON file. The state of the wallet should be able to be restored from this file, which will contain keys, accounts (aliases, addresses, recent transfer history), etc.
- Should this file contain the mnemonic, or is it assumed it has already been stored somewhere safe?

### Restore wallet state
The user should be able to import an exported JSON file, restoring the wallet to a previous saved state.

**Comment by mateuszjasiuk** [comment]
Already done!
