### ISSUE TITLE
Namadillo: Use indexer pagination

### ISSUE THREAD

**Issue by emccorson** [anoma/namada-interface#916]
When fetching the list of proposals or the list of validators, we are currently not using the indexer's pagination. We need to fetch by page and show the pagination in the validators/proposals tables. Without this we are getting the wrong data (e.g. only the first page of validators).

**Comment by pedrorezende** [comment]
@emccorson for the V1, we've decided to get the full list of validators from the server, without pagination (#910). It will help us to avoid to implement sort, randomization and filtering in the indexer. This might change in the future, when we get the final number of validators
