### ISSUE TITLE
Extension: Bug - Service worker goes inactive while user is logged in

### ISSUE THREAD

**Issue by jurevans** [anoma/namada-interface#92]
When the extension is running as `manifest_version: 3`, with a service worker, Chrome does not guarantee that the service worker will remain active during the user's session, which can lead to deauthentication, even after a short period of inactivity. Unlike persistent `background` pages in Firefox (`manifest: 2`) service workers will inevitably terminate (this is also true in Firefox `manifest: 3`).

See <https://stackoverflow.com/questions/66618136/persistent-service-worker-in-chrome-extension> for information on how to work around this, and to achieve better control over the lifetime of the service worker. This is not an issue in Manifest v2 extensions, therefore, Firefox is unaffected by this.

This bug can be observed by running the extension in a Chrome-based browser, as of https://github.com/anoma/namada-interface/pull/84

Steps to recreate:
1. Create an account in the extension (or log in to an existing account)
2. Navigate to `Derive new account` screen
3. Wait until the service worker becomes inactive (this can be viewed from the `Manage Extensions` page)
4. Attempt to derive a new address, and observe that it fails (which is due to the service worker no longer having the user's credentials)

It may be good in the interim to periodically check that the extension is authenticated before performing further actions, but the best solution is to keep the service worker alive until 1) the user manually locks the extension, or 2) a period of inactivity that we have determined has passed

**NOTE** - This is resolved when the content-scripts establish a port to the background (service-worker) using the `browser.runtime.connect()` API. This should be performed either on `Anoma.connect("chainId")`, or upon successful login. Either of those will re-establish the port and keep the service worker alive for a default of 5 minutes, which is reasonable for a session length.
- It may be worth it at this point to update the `ExtensionRouter` class to establish all connections over a port with the `runtime.connect()` API, which would, by default, maintain a connection to the service worker. This may be the cleanest long-term solution.

**Comment by memasdeligeorgakis** [comment]
In google's [documentation for migrating from manifest v2 to v3](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#events) it is stated: *"service workers are a special execution environment that are started to handle events they're interested in and are terminated when they're no longer needed"*

It also [says](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/#state): *"One of the main things to get used to when adopting service workers is that they are short-lived execution environments. In more practical terms, an extension's service worker will start up, do some work, and get terminated repeatedly throughout a user's browser session. This poses a challenge to extension developers accustomed to long-lived background pages as application data is not immediately available in global variables."*

I assume that this PR is addressing this *"terminated when they're no longer needed"*? If that is the case I am wondering if we are trying to persist a state in with/in service workers in a way that is not intended 🤔

**Comment by jurevans** [comment]
I'm closing this as the behavior of the service worker isn't necessarily a bug. I will open a separate issue to implement a user flow that works better _with_ service workers instead of implementing work-arounds to make it behave like Manifest v2 background pages. (i.e., it should be more _stateless_) This will need to be addressed with functionality to prompt the user for their password anytime the keyring needs to be unlocked.
